# Generated by Django 2.2 on 2019-04-18 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bboard.City', verbose_name='Город'),
        ),
    ]
